"""Regenerate the synthetic test images under ``tests/fixtures/images/``.

    python tests/fixtures/_generate_images.py

> **These are not photographs of anything.** They are geometric patterns - gradients,
> checkerboards, noise - generated by this script to exercise the preprocessing code
> paths. None depicts pottery, an inscription, or any archaeological object, and none
> may ever be treated as research data. See ``tests/fixtures/README.md``.

Each file exists to drive one branch of the pipeline: a colour mode, a format, an EXIF
orientation, or a failure. They are kept small (mostly 64x48) so the repository stays
light.

Output is deterministic: the noise uses a fixed seed, and no timestamps are written.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE / "images"

W, H = 64, 48
SEED = 20260922


def _gradient_rgb(w: int = W, h: int = H) -> Image.Image:
    """A deterministic RGB gradient with a hard edge, so sharpness is measurable."""
    xs = np.linspace(0, 255, w, dtype=np.float64)
    ys = np.linspace(0, 255, h, dtype=np.float64)
    r = np.tile(xs, (h, 1))
    g = np.tile(ys[:, None], (1, w))
    b = np.full((h, w), 128.0)
    array = np.stack([r, g, b], axis=2)
    # A hard-edged block: gives the Laplacian something to find.
    array[h // 4 : h // 2, w // 4 : w // 2] = [255, 255, 255]
    return Image.fromarray(array.round().astype(np.uint8), mode="RGB")


def _checkerboard(w: int = W, h: int = H, cell: int = 8) -> Image.Image:
    ys, xs = np.mgrid[0:h, 0:w]
    board = (((xs // cell) + (ys // cell)) % 2 * 255).astype(np.uint8)
    return Image.fromarray(board, mode="L")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(SEED)
    written: list[tuple[str, str]] = []

    def record(name: str, why: str) -> None:
        written.append((name, why))

    rgb = _gradient_rgb()

    # -- formats --------------------------------------------------------------
    rgb.save(OUT / "rgb_gradient.png", format="PNG", optimize=False)
    record("rgb_gradient.png", "baseline RGB PNG")

    rgb.save(OUT / "rgb_gradient.jpg", format="JPEG", quality=92)
    record("rgb_gradient.jpg", "baseline RGB JPEG")

    rgb.save(OUT / "rgb_gradient.tif", format="TIFF")
    record("rgb_gradient.tif", "baseline RGB TIFF")

    rgb.save(OUT / "rgb_gradient.bmp", format="BMP")
    record("rgb_gradient.bmp", "baseline RGB BMP")

    # -- colour modes ---------------------------------------------------------
    _checkerboard().save(OUT / "grayscale_checker.png", format="PNG", optimize=False)
    record("grayscale_checker.png", "mode L - grayscale")

    rgba = rgb.convert("RGBA")
    alpha = np.asarray(rgba).copy()
    alpha[:, : W // 2, 3] = 0          # left half fully transparent
    Image.fromarray(alpha, mode="RGBA").save(
        OUT / "rgba_transparent.png", format="PNG", optimize=False
    )
    record("rgba_transparent.png", "mode RGBA - half transparent, tests flattening")

    rgb.convert("P", palette=Image.Palette.ADAPTIVE, colors=64).save(
        OUT / "palette.png", format="PNG", optimize=False
    )
    record("palette.png", "mode P - palette")

    rgb.convert("CMYK").save(OUT / "cmyk.jpg", format="JPEG", quality=92)
    record("cmyk.jpg", "mode CMYK JPEG")

    sixteen = (np.tile(np.linspace(0, 65535, W), (H, 1))).round().astype(np.uint16)
    # mode is inferred from the uint16 dtype; passing it explicitly is deprecated.
    Image.fromarray(sixteen).save(OUT / "grayscale_16bit.tif", format="TIFF")
    record("grayscale_16bit.tif", "16-bit grayscale TIFF - tests bit-depth reduction")

    bilevel = _checkerboard().convert("1")
    bilevel.save(OUT / "bilevel.png", format="PNG", optimize=False)
    record("bilevel.png", "mode 1 - bilevel")

    # -- EXIF orientation -----------------------------------------------------
    # Orientation 6 = rotate 90 CW on display. The stored pixels are landscape;
    # a correct reader shows them portrait.
    oriented = _gradient_rgb(W, H)
    exif = Image.Exif()
    exif[0x0112] = 6
    oriented.save(OUT / "exif_orientation_6.jpg", format="JPEG", quality=92, exif=exif)
    record("exif_orientation_6.jpg", "EXIF orientation 6 - must be rotated on load")

    exif_1 = Image.Exif()
    exif_1[0x0112] = 1
    oriented.save(OUT / "exif_orientation_1.jpg", format="JPEG", quality=92, exif=exif_1)
    record("exif_orientation_1.jpg", "EXIF orientation 1 - no rotation, control case")

    # -- geometry edge cases --------------------------------------------------
    _gradient_rgb(40, 40).save(OUT / "small_40x40.png", format="PNG", optimize=False)
    record("small_40x40.png", "small but above the floor - triggers upscaling")

    _gradient_rgb(8, 8).save(OUT / "tiny_8x8.png", format="PNG", optimize=False)
    record("tiny_8x8.png", "below the 32px floor - must be REJECTED")

    # Below the floor: rejected before quality is ever measured.
    _gradient_rgb(200, 10).save(OUT / "wide_200x10.png", format="PNG", optimize=False)
    record("wide_200x10.png", "20:1 but 10px short side - REJECTED by the floor")

    # Above the floor: reaches the quality stage and trips extreme_aspect_ratio.
    _gradient_rgb(400, 40).save(OUT / "wide_400x40.png", format="PNG", optimize=False)
    record("wide_400x40.png", "10:1, short side 40px - passes, flags extreme aspect")

    _gradient_rgb(40, 400).save(OUT / "tall_40x400.png", format="PNG", optimize=False)
    record("tall_40x400.png", "10:1 portrait - passes, flags extreme aspect")

    # -- quality edge cases ---------------------------------------------------
    Image.fromarray(np.full((H, W, 3), 8, dtype=np.uint8), mode="RGB").save(
        OUT / "dark_flat.png", format="PNG", optimize=False
    )
    record("dark_flat.png", "very dark, no contrast")

    Image.fromarray(np.full((H, W, 3), 250, dtype=np.uint8), mode="RGB").save(
        OUT / "bright_flat.png", format="PNG", optimize=False
    )
    record("bright_flat.png", "very bright, no contrast")

    noise = rng.integers(0, 256, size=(H, W, 3), dtype=np.uint8)
    Image.fromarray(noise, mode="RGB").save(OUT / "noise_sharp.png", format="PNG", optimize=False)
    record("noise_sharp.png", "high Laplacian variance - the 'sharp' end of the scale")

    smooth = np.tile(np.linspace(100, 140, W), (H, 1))
    Image.fromarray(
        np.stack([smooth] * 3, axis=2).round().astype(np.uint8), mode="RGB"
    ).save(OUT / "smooth_blurry.png", format="PNG", optimize=False)
    record("smooth_blurry.png", "near-zero Laplacian variance - the 'blurry' end")

    gray_as_rgb = np.stack([np.asarray(_checkerboard())] * 3, axis=2)
    Image.fromarray(gray_as_rgb, mode="RGB").save(
        OUT / "rgb_but_grayscale.png", format="PNG", optimize=False
    )
    record("rgb_but_grayscale.png", "RGB mode, identical channels - a grayscale scan")

    # -- failure cases --------------------------------------------------------
    jpeg_bytes = (OUT / "rgb_gradient.jpg").read_bytes()
    (OUT / "truncated.jpg").write_bytes(jpeg_bytes[: len(jpeg_bytes) // 2])
    record("truncated.jpg", "CORRUPT: JPEG cut in half - must be rejected, not repaired")

    (OUT / "not_an_image.jpg").write_text(
        "SYNTHETIC FIXTURE. This is plain text with a .jpg extension. "
        "It is not an image and must be rejected.\n",
        encoding="utf-8",
    )
    record("not_an_image.jpg", "text pretending to be a JPEG - must be rejected")

    (OUT / "unsupported.txt").write_text(
        "SYNTHETIC FIXTURE. Unsupported format test file.\n", encoding="utf-8"
    )
    record("unsupported.txt", "unsupported extension and content")

    (OUT / "empty.png").write_bytes(b"")
    record("empty.png", "zero bytes - must be rejected")

    # A PNG whose extension lies: real content is JPEG.
    (OUT / "actually_jpeg.png").write_bytes(jpeg_bytes)
    record("actually_jpeg.png", "extension/content mismatch - warns but still loads")

    manifest = {
        "_WARNING": (
            "SYNTHETIC TEST IMAGES. Generated by tests/fixtures/_generate_images.py. "
            "These are geometric patterns, not photographs. None depicts pottery, an "
            "inscription, or any archaeological object. Never research data."
        ),
        "seed": SEED,
        "files": {name: why for name, why in written},
    }
    import json

    (OUT / "MANIFEST.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )

    for name, why in written:
        size = (OUT / name).stat().st_size
        print(f"  {name:<28} {size:>7,} bytes   {why}")
    print(f"\n{len(written)} synthetic image(s) written to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
